# Site settings
title: Eugene Cheung | Developer + Designer
email: ey.cheung@outlook.com
description: A passionate developer with an eye for beautiful creations.
baseurl: /v1
url: http://echeung.me
twitter_username: arkon
github_username: arkon

# Build settings
markdown: kramdown
permalink: pretty

# Enable asset processing
assets:
  baseurl: /v1/assets
  compress:
    css: true
    js: true
  js_compressor: uglifier
  css_compressor: sass
